### ISSUE TITLE
Minimal Event documentation

### ISSUE THREAD

**Issue by airguru** [cunnane/xloil#24]
I am trying to implement a handler to the `SheetBeforeDoubleClick` event. The documentation seems to be non-existing, but it would be enough if there are some very general guidelines on how to approach the event parameters and what is the event handler expected to return. So far with this test code:

```
def click_handler(worksheet, target, cancel):
    worksheet['P4'].value = 'TEST'
    return cancel
    
xlo.event.SheetBeforeDoubleClick += click_handler
```

I have
```
[error] During Event SheetBeforeDoubleClick: return_value_policy = copy, but type is non-copyable! (compile in debug mode for details)
```

**Comment by cunnane** [comment]
I noticed the python module reference doc was completely broken on ReadTheDocs.  I've fixed this and improved the docs for Events, see the [latest docs here](https://xloil.readthedocs.io/en/latest/xlOil_Python/Concepts.html#events).

You shouldn't return a value from a event handler.  Instead set `cancel.value=True` if you want to cancel the event.

**Comment by cunnane** [comment]
Also note there are some examples of event handling the *PythonTest* example/test.  I'm going to tentatively close this, let me know if you're still having problems.

**Comment by airguru** [comment]
Sorry for being a bit late on this!

Thank you very much for fixing the documentation! I was under impression that it's not yet complete. 

However, from your suggestion I understand that my only mistake might have been returning a value from the event. So I am no longer doing that, but I still get the same error. I tried setting `cancel.value` both `True` and `False` and not setting it at all, no difference. I am trying this on the newest 0.16.4.

The `WorkbookNewSheet` event from the documentation seems to work though, so the problem is not in events in general.
```
def greet(workbook, worksheet):
    xlo.Range(f"[{workbook}]{worksheet}!A1").value = "Hello!"   # small bug in doc: ".value" needs to be added here for this to work

xlo.event.WorkbookNewSheet += greet
```

**Comment by cunnane** [comment]
Sorry, I should have checked this more thoroughly - there's definitely an issue here

**Comment by cunnane** [comment]
This has been fixed in xlOil 0.17
