### ISSUE TITLE
Can't get started with xlOil

### ISSUE THREAD

**Issue by dutch-rob** [cunnane/xloil#31]
I was really looking forward for xlOil to work here, it looks really great!

When I try to follow the getting started with xlOil, I run into some problems.

The "xlOil install" doesn't work for me, I assume because my work environment doesn't allow access to the Windows registry.

I dropped xloil.xll on an Excel window, which gave the following message:

![image](https://user-images.githubusercontent.com/9722703/216727773-1be470cf-601d-487e-b7f3-260622890ed0.png)

Which made me wonder: Would it be possible to get that digital signature?

When I clicked on "Enable this add-in for this session only" I got the following errors:

![image](https://user-images.githubusercontent.com/9722703/216728062-170afa01-969e-40aa-9a52-da5652044b98.png)

For if the screenshot doesn't come through well:
[15:12:35] [error] Failed to register func xloImport: bad allocation
[15:12:35] [error] Failed to register func xloAttrObj: In Win32 builds, there is a limit of 16 args for non-local UDFs. Raise a github issue if this is a problem!
[15:12:35] [error] Failed to register func xloPyDebug: bad allocation
[15:12:35] [error] Failed to register func xloAttr: In Win32 builds, there is a limit of 16 args for non-local UDFs. Raise a github issue if this is a problem!
[15:12:35] [error] Registration failed for: xloImport
[15:12:35] [error] Registration failed for: xloAttrObj
[15:12:35] [error] Registration failed for: xloPyDebug
[15:12:35] [error] Registration failed for: xloAttr

I get an "xlOil Py" menu:

![image](https://user-images.githubusercontent.com/9722703/216728682-d0b43743-e992-4782-9510-b4fb810db6a4.png)

But the test function does not get recognized.

It seems like it is quite close to working well.
I wonder: Can this only work with admin privilege or might it be possible to get it to work with a bit of tinkering?

I got xlOil version 0.17.0 with a pip install; using Python 3.10 32 bits [xlOil wouldn't install with Python 3.11 32 bits - 32 bits because MS Office installed here is Microsoft Excel for Microsoft 365 MSO (Version 2212 Build 16.0.15928.20196) 32-bit] under Windows 10 Pro.

**Comment by cunnane** [comment]
Thanks for trying with this, unfortunately you were rather against the odds as the 32-bit build of v0.17.0 was broken.  I've fixed this and added support for python 3.11 in v0.17.1 which is now on pip.   The install script doesn't write to the registry, only read, so probably won't be blocked by security but let me know if you get errors with that.

To do a manual install you'd need to copy xlOil.ini to %APPDATA%\xlOil, then edit the copy so that PYTHONEXECUTABLE points to your python distribution and XLOIL_PATH to the directory containing xlOil.dll

**Comment by dutch-rob** [comment]
Thanks very much!

I could not install xlOil and it doesn't give any error when opening Excel.

BTW: 
- I noticed over the weekend that my work did put 64 bit Office on my laptop so I am going to ask them to bring my desktop up to date as well.
- Currently my Excel here shows the xlOil ribbon fine but it does not seem to find the Python function if I try either example https://xloil.readthedocs.io/en/stable/xlOil_Python/GettingStarted.html#my-first-xloil-module or https://xloil.readthedocs.io/en/stable/xlOil_Python/GettingStarted.html#my-first-workbook-module but I am going to look into that more after I got our help desk here to change my MSOffice to 64 bit and reinstall xlOil for 64 bit.
I will update this text when I find out more.
- xlOil appears to work great on my own PC at home. I really like it!!

Again, thanks very much!!

**Comment by cunnane** [comment]
Glad it's working on 33% of your devices, hopefully we can get that a little higher!

When you say "could not install" what happens exactly?  I presume you've trying 0.17.1?

When you try the samples, does a log file get created at `%APPDATA%\xlOil\xlOil.log`?  If not, try changing the debug level in the xlOil Ribbon (and restart Excel and try again).

**Comment by dutch-rob** [comment]
Oh sorry, "could not install" should have been "could install" (I corrected my previous message).
Yes, I am now working with version 0.17.1
I have not got around to getting 64 bits MSOffice, so I have no further update yet. (I am not asking you to do anything now.)
Thanks!!

**Comment by dutch-rob** [comment]
Update:
Now xlOil also works fine on my work laptop, which had already 64 bits Excel.
It took some time to get them to install 64 bits Excel on my desktop PC at work but I have that now. It still shows the same issue:
The xlOil ribbon appears to work well but Excel does not appear to find the .py with same filename on same directory.
I can't see why it works well on my laptop but not on desktop that have a very similar setup of directory structure, lack of admin privilege, and same windows, ms-office, and python version. If you have a clue, please let me know but I can't expect that you do.
Thanks for the help either way!

**Comment by cunnane** [comment]
Do you have anything in `%APPDATA%\xlOil\xlOil.log` when the log level is set to debug in the ribbon?

**Comment by dutch-rob** [comment]
The short answer is: no.
When I set debug to 'pdb' the log file remains empty. When selecting either of the options 'debugpy' or 'vscode' I get error messages saying that I don't have those.

**Comment by cunnane** [comment]
Sorry, I mean when the log _level_ is set to 'debug' rather than setting the choice of debugger, i.e. change the upper of the two combo boxes.

**Comment by dutch-rob** [comment]
Oh I apologize, I misread your earlier message.
It doesn't seem to show an attempt to find MyBook.py
[xlOil.log](https://github.com/cunnane/xloil/files/10711232/xlOil.log)

I also tried adding "MyBook" to the "Load Modules". Then I also added MyBook.py not only to the directory of the Excel file but also to the python package directory (...\Python311\Lib\site-packages\xloil), expecting that either or both of those places would be among the search paths. that led to an error message popup and this log:
[xlOil.log](https://github.com/cunnane/xloil/files/10711421/xlOil.log)

I also tried a few variants of adding a search path to the search paths field in the ribbon but could not resolve the problem. I could not find in the documentation what should be in the search paths field: Should the semicolon that is there at fresh install remain, if so, before or after the added path, should the path be in single or double quotation marks, should I use '\', '\\', or '/' to separate parts of the path?
BTW: the error that I caused by trying to add a search path, gets saved to the .ini, and makes the ribbon not load the next time of starting Excel so that it is not possible to correct my error. I could resolve that by removing the .ini and reinstalling. I suppose it would also be possible to edit the .ini but I didn't want to risk messing that up.

**Comment by cunnane** [comment]
There's not much to go on in the logs: as you note there's no acknowledgement that xlOil even attempted to load your workbook module, and everything else seems to be as expected. I've added some more detailed logging around the module load in 0.17.2 which hopefully can root out the issue if you wouldn't mind trying.

**Comment by cunnane** [comment]
Thanks for doing all the hard debugging work here!  I think it should be fairly straightforward to load a py file from an http address like sharepoint - I'll try that aproach first rather than trying to figure out the synced path, which seems quite hard.

xlOil will only try to load *MyBook.py* from the folder containing *MyBook.xlsx*, it doesn't search the usual `sys.path`.  This is by design since if you happed to create an workbook with the same name as as python module, you may run into strange issues!

**Comment by cunnane** [comment]
The "search paths" in the ribbon are appended to the python `sys.path` however when loading a workbook-linked module, xlOil does not use the search paths and only tries to load the module from the same directory as the workbook.

In v0.17.4 which I've just released, xlOil should be able to load OneDrive/Sharepoint files from locally synced copies or directly  over http.

**Comment by dutch-rob** [comment]
Great, thanks very much! It works great now, also on my PC at work.

**Comment by cunnane** [comment]
Great news, thanks for persisting and helping improve the software!
